### PR TITLE
 Vibration changes and External Audio

### PR DESCRIPTION
**Pull request by scott0123**
Arrows key changes should also trigger vibration.
The "hard vibrate" was also a bit lacking, so that has been changed.

### CODE REVIEW

**Comment by scott0123** [comment]
Also added support for external audio. (Playing audio from a different app)

**Comment by scott0123** [comment]
I went back to check out issue #13 and it seems like using the taptic engine on supported devices was a community decision. I understand your concern now, but hear me out:
The strongest level of haptic feedback - "impactOccurred" - which is on the heavy setting feels less impactful than even the standard vibration on the light setting. Wouldn't it make more sense to put the haptic feedback version on the light setting, and override the heavy setting with the standard vibrations regardless for people that prefer that? Adding another "Taptic Engine toggle" might be too complicated for non-technical users who don't really know what they want.

If you disagree, I still happy to revert that particular change.

**Comment by FrederickGeek8** [comment]
Sorry, but I think I would prefer a Taptic Engine Setting in Settings. Again, thank you for your pull request.

**Comment by scott0123** [comment]
Done and done. This PR fixes and closes #62

There seems to be issues with button vibration not working after the app suspension, which has been noted in #73 and #78. The external audio is also similarly affected by the issue described in #78. This is not due to my implementation, but rather due to something breaking after resuming which needs to be looked into.

Feel free to merge this now.

**Pull request merged**
