### PR TITLE
DeSmuME 0.9.11 Update

### LINKED ISSUE #4: Ace Attorney Games 3D Sections Error With Screenshot, Savestate and ROM (AAI)
REPOST FROM PREVIOUS GITHUB. Original post by AmaidoPro. 

There has been already a couple of people complaining about 3D parts in ace attorney games, the problem is not being able to examine certain objects (on this tape you need to examine the blood), so without further to do, here is all you need to attempt this yourself (Ace Attorney Investigations)

Screenshot: https://user-images.githubusercontent.com/38716199/39230679-4bb91d4c-485f-11e8-9c5d-d7cfbec25bda.png

ROM: https://drive.google.com/open?id=1T4ljKskZegy8EPBzPstm7GTyMmbMPfom

Save State (Auto-Save): https://drive.google.com/open?id=1aRkIo2HdBIaAhvA1-2ZTyPfL8byvjuFu

I would really like to get past this scene in Ace Attorney Investigations. All the above should be enough to check it yourself. I would really appreciate if you could fix this as soon as possible. Thanks for the support iNDS Team!

### LINKED ISSUE #43: Desmume version
I know updating to 0.9.11 is on the list, but when is it estimated to happen? I really wanna play ace attorney, but the examinations don’t work 0.9.10.

Also, just a note in case you need it, I got the emulator from iEmulators.

EDIT: Okay, I’ve realized that the iEmulators version is still at version 1.3.5, so does that one just never get updated? Does that mean I have to get it a different way to keep it updated?

### LINKED ISSUE #49: Wario Ware D.I.Y. Doesn’t work.
I pretty sure you already know of this sort of problem, but can we expect it to get fixed?

### PR DESCRIPTION
**Pull request by FrederickGeek8**
Okay, I want to start off by saying that **I will really want people to test this.** This pull request updates the DeSmuME core to version 0.9.11, which should fix or improve problems and performance in games. One such game that is improved by 0.9.11 is WarioWare D.I.Y, which resolves #49. This upgrade was first requested in #43, thus this PR resolves #43.

**Is this iNDS 2.0?**
No. iNDS 2.0 was a complete redesign that was undertaken by William Cobb. This is a naive replacement of the DeSmuME core with the latest stable version of DeSmuME. _Do not_ expect the same feature set that was promised in iNDS 2.0 to be present in this pull request.

**Does this fix #4?**
~~Unfortunately, as near as I can tell, this does not resolve #4. It does change the result of the issue, however, the affected area of the game is still impassable.~~
~~Thanks to @cbranch, issues regarding the 3D sections in Apollo Justice have been resolved.~~
This pull request now officially fixes #4. Special thanks to @cbranch for his wonderful coordinates fix.

### CODE REVIEW

**Comment by FrederickGeek8** [comment]
One caveat that has been found is that older saves no longer work.

**Comment by Dry05** [comment]
Could you please send me a compiled version? I’m having some compiling issues due to the pod repo update ssl stuff. I can resign all myself

**Comment by Dry05** [comment]
Thank you, it runs great on iPhone X! I tested Pokémon heart gold my favorite, which is known to have some issues and I had them before. Sound syncs good finally. No graphical blackouts. Perfect!

**Comment by cbranch** [comment]
Compared to master, on an iPhone 6S I notice significantly more obvious flickering: black lines near the top of the lower screen, and occasional black lines randomly on the top screen. This is with Ace Attorney (not tried other games yet).

I don't notice see this on DeSmuME 0.9.11 on MacOS. There isn't a vsync option in iNDS, although I'm not convinced that's the answer...

**Comment by FrederickGeek8** [comment]
Good to know @cbranch. I’ll see if I can knock out #56 before merging. I’m hoping it’s a relatively straightforward issue to fix...

**Comment by Dry05** [comment]
When using 1.9.1 I can use my gamesave dumped from the cartridge. When using 1.9.2 I can’t it overwrites it. I guess this has something to do with the desmume core issue you’re talking about?

**Comment by FrederickGeek8** [comment]
@Dry05 I believe that 1.9.2b2 should be able to load in-game saves, though savestates (created through Save State menu) are not working. Is this the behavior you observed?

**Comment by Dry05** [comment]
The steps I did, I dumped my .sav from my heartgold cartridge. And I renamed .sav to .dsv and tried loading it with iNDS. On 1.9.1 it works on 1.9.2 beta 1 and I also tried beta 2 it doesn’t work

**Comment by fmontedori** [comment]
Hello Frederick, in-game saves not working for me too on 1.9.1 freshly compiled and iOS 12.
Well the game saved but if I launch Normally can't continue.
Tried beta2 without success.
Saves States working without issue.

I'm not an developper expert but if I can help, feel free to contact me.

**Comment by FrederickGeek8** [comment]
@fmontedori If you are having issues with versions other than the one in this pull request, please open a new issue.

**Comment by FrederickGeek8** [comment]
@Dry05 's issue was solved by importing then exporting from desktop DeSmuME 0.9.11. I can look into the cause later, but it might be good to merge changes soon in light of the development on #4.

**Comment by FrederickGeek8** [comment]
Would anybody be opposed to me merging this PR in the next day or so?

**Pull request merged**
