### PR TITLE
Fix microphone input

### PR DESCRIPTION
**Pull request by kmilner**
DeSmuME expects 7 bit input from the microphone, while iNDS was providing 8 bit values. iOS also requires a reason stated in the info.plist to ask for microphone permission; adding that allows the permission request to work.

I also fixed the debug sample rate calculation because it was inexplicably resetting the values before calculating the sample rate, and doesn't need to done unless being used for debugging (micSampleRate is not used anywhere else).

### CODE REVIEW

**Comment by FrederickGeek8** [comment]
I'll check this out tomorrow. Thank you!

**Comment by FrederickGeek8** [comment]
Okay, so I wasn't able to get it to work without modifications. I believe that the permissions blocks that you can find in @genkino 's [fork](https://github.com/genkino/iNDS/commit/f88f51ab7e28d34642f111097bdd47849d93413e) fixes the issue with your PR. More specifically, the blocks in `iNDSROMTableViewController.m` [(here)](https://github.com/genkino/iNDS/commit/f88f51ab7e28d34642f111097bdd47849d93413e#diff-c52ba6e6372c440aeae50ef8c8ea0014) and `mic.mm` [(here)](https://github.com/genkino/iNDS/commit/f88f51ab7e28d34642f111097bdd47849d93413e#diff-702055e84e789e916bce76dd0ecb0804).

Other than that, this PR looks good. I'll merge it after those changes!

**Comment by FrederickGeek8** [comment]
UPDATE: With those changes, the audio seems to not be present at times (regardless of whether my mute switch is on/off). I'll investigate it...

**Comment by kmilner** [comment]
w.r.t your second update, If the microphone is off in the settings before the game starts reading it then the audio works normally. Turning it off after it has been read doesn't seem to help though, and same (I think) with turning it off before loading a save state that previously had it on. Very strange...

**Comment by FrederickGeek8** [comment]
Regarding that one second of audio, I think it is a result of "kickstarting" the SPU when the settings "change" (you can see it at [emu.cpp:309](https://github.com/iNDS-Team/iNDS/blob/851c63b19636ea5fb01648cb42c4da4b28d93169/iNDS/core/emu.cpp#L309)).

I have found something interesting! If I remove the if statement at [emu.cpp:335](https://github.com/iNDS-Team/iNDS/blob/851c63b19636ea5fb01648cb42c4da4b28d93169/iNDS/core/emu.cpp#L335), which mutes the audio if the settings say so, then it seems to "fix" the issue. This isn't a fix by any means, but it might help us track down the issue.

**Comment by kmilner** [comment]
It appears to be because of the way the mute detector works, according to this: https://stackoverflow.com/questions/17956497/audioservicesplaysystemsound-while-avcapturesession-is-active

It is not possible to play using AudioServicesPlaySystemSound when there's a recording session, but the mute detector uses the timing of that function call to determine if sound is muted or not. 

I could patch that to use a different method, but is it even necessary to know if the mute switch is on? I realize it means sound would be computed even when the mute switch is on, but if that is causing slowdown for someone they could disable audio from the settings instead.

**Comment by kmilner** [comment]
Here's a version with the mute switch detection removed, if you want to try it out.

**Comment by FrederickGeek8** [comment]
Although it would be nice to keep the mute detector present, I would be fine parting with it, at least for the time being.

**Pull request merged**
